"""
Centralized Strategy Instruction Schema Definitions and Validation.

This module defines the parquet schema for strategy instructions,
ensuring consistency between strategy-service (producer) and
execution-service (consumer).

Strategy instructions are generated by strategy-service and consumed
by execution-service for execution and alpha calculation.

Key Design Principles:
- instruction_type is MANDATORY (TRADE, SWAP, LEND, BORROW, etc.)
- instruction_id is MANDATORY (unique identifier)
- quantity is MANDATORY (not notional)
- direction is REQUIRED only for TRADE/SWAP instruction types
- ATOMIC instructions can bundle on-chain instructions (NOT TRADE)
"""
# pyright: reportUnknownMemberType=false, reportUnknownVariableType=false, reportUnknownParameterType=false, reportUnknownArgumentType=false, reportAny=false
# Reason: pandas DataFrame operations, pyarrow (pa.Table, pq.read_table), and
# json.loads return types have incomplete stubs. Documented in QUALITY_GATE_BYPASS_AUDIT.md.

import json
import logging
from pathlib import Path

import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from unified_config_interface import validate_strategy_id

logger = logging.getLogger(__name__)

# =============================================================================
# INSTRUCTION TYPES
# =============================================================================

# Valid instruction types
VALID_INSTRUCTION_TYPES = [
    "TRADE",  # CeFi CLOB execution (requires direction)
    "SWAP",  # DEX swap (requires direction)
    "LEND",  # Lending protocol deposit
    "BORROW",  # Lending protocol borrow
    "WITHDRAW",  # DEPRECATED: Balance changes handled by strategy layer. Use UNSTAKE for staking withdrawals.
    "REPAY",  # Repay borrowed amount
    "STAKE",  # Staking deposit
    "UNSTAKE",  # Staking withdrawal
    "TRANSFER",  # Asset transfer between wallets/chains
    "FLASH_BORROW",  # Flash loan borrow (must pair with FLASH_REPAY)
    "FLASH_REPAY",  # Flash loan repay
    "ATOMIC",  # Bundle of on-chain instructions (NOT TRADE)
    "HEARTBEAT",  # Interval heartbeat - strategy alive, no action
    "HOLD",  # Explicitly hold current position
    "NO_ACTION",  # Alias for HEARTBEAT
]

# DEPRECATED instruction types - kept for backward compatibility
DEPRECATED_INSTRUCTION_TYPES = ["WITHDRAW"]

# Instruction types that can be bundled into ATOMIC transactions
# TRADE cannot be atomic (it's CeFi/off-chain CLOB execution)
ATOMIC_COMPATIBLE_TYPES = [
    "SWAP",
    "LEND",
    "BORROW",
    "WITHDRAW",
    "REPAY",
    "STAKE",
    "UNSTAKE",
    "TRANSFER",
    "FLASH_BORROW",
    "FLASH_REPAY",
]

# Instruction types that REQUIRE direction (-1 or 1)
DIRECTION_REQUIRED_TYPES = ["TRADE", "SWAP"]

# Instruction types where direction=0 is allowed (heartbeat/hold/no-action)
DIRECTION_ZERO_ALLOWED_TYPES = ["HEARTBEAT", "NO_ACTION", "HOLD"]

# Valid direction values for TRADE/SWAP
VALID_DIRECTIONS = [-1, 1]  # -1=sell/short, 1=buy/long
VALID_DIRECTIONS_WITH_ZERO = [-1, 0, 1]  # 0 allowed for heartbeat types

# =============================================================================
# COLUMN DEFINITIONS
# =============================================================================

INSTRUCTION_COLUMNS = {
    # === REQUIRED FOR ALL ===
    "timestamp": {
        "type": "int64",
        "required": True,
        "description": "Instruction generation timestamp (nanoseconds UTC)",
    },
    "instruction_id": {  # RENAMED from signal_id - NOW REQUIRED
        "type": "string",
        "required": True,
        "description": "Unique instruction identifier",
    },
    "instruction_type": {
        "type": "string",
        "required": True,  # NOW REQUIRED
        "description": "Instruction type (TRADE, SWAP, LEND, BORROW, STAKE, etc.)",
    },
    "instrument_id": {
        "type": "string",
        "required": True,
        "description": "Canonical instrument ID (VENUE:TYPE:SYMBOL)",
    },
    "strategy_id": {
        "type": "string",
        "required": True,
        "description": "Strategy ID (CATEGORY_ASSET_desc_MODE_TF_VERSION)",
    },
    "quantity": {
        "type": "float64",
        "required": True,  # NOW REQUIRED (not notional)
        "description": "Execution quantity (absolute value, must be > 0)",
    },
    "benchmark_price": {
        "type": "float64",
        "required": True,
        "description": "Benchmark price for execution alpha calculation. MUST be > 0.",
    },
    # === CONDITIONAL: Required for TRADE/SWAP ===
    "direction": {
        "type": "int8",  # -1 (SELL/SHORT), 1 (BUY/LONG)
        "required": False,  # Required only for TRADE/SWAP via validation
        "description": "Direction: -1=sell/short, 1=buy/long. REQUIRED for TRADE/SWAP.",
    },
    # === OPTIONAL: Price bounds ===
    "price_cap": {
        "type": "float64",
        "required": False,
        "description": "Maximum price for entry (buy limit ceiling)",
    },
    "price_floor": {
        "type": "float64",
        "required": False,
        "description": "Minimum price for entry (sell limit floor)",
    },
    # === OPTIONAL: Exit targets (for exit alpha) ===
    "take_profit_price": {
        "type": "float64",
        "required": False,
        "description": "Take profit price (included in exit alpha if set)",
    },
    "stop_loss_price": {
        "type": "float64",
        "required": False,
        "description": "Stop loss price (included in exit alpha if set)",
    },
    "candle_close_price": {
        "type": "float64",
        "required": False,
        "description": "Candle close price for SCE mode fallback exit",
    },
    # === OPTIONAL: Analytics ===
    "confidence": {
        "type": "float64",
        "required": False,
        "description": "Instruction confidence (0-1) for analytics/quality correlation",
    },
    "urgency": {
        "type": "float64",
        "required": False,
        "description": "Execution urgency (0-1)",
    },
    # === OPTIONAL: Chaining ===
    "chain_id": {
        "type": "string",
        "required": False,
        "description": "Links related instructions (e.g., swap->lend->stake sequence)",
    },
    "chain_sequence": {
        "type": "int32",
        "required": False,
        "description": "Order in chain (1, 2, 3...)",
    },
    # === ATOMIC ONLY ===
    "nested_instructions": {
        "type": "string",  # JSON array of nested instructions
        "required": False,
        "description": "For ATOMIC type: JSON array of nested on-chain instructions",
    },
}

# PyArrow schema for instruction parquet files (pa.field/pa.int64 etc. have incomplete stubs)
INSTRUCTION_SCHEMA: pa.Schema = pa.schema(
    [
        pa.field("timestamp", pa.int64(), nullable=False),
        pa.field("instruction_id", pa.string(), nullable=False),
        pa.field("instruction_type", pa.string(), nullable=False),
        pa.field("instrument_id", pa.string(), nullable=False),
        pa.field("strategy_id", pa.string(), nullable=False),
        pa.field("quantity", pa.float64(), nullable=False),
        pa.field("benchmark_price", pa.float64(), nullable=False),
        pa.field("direction", pa.int8(), nullable=True),
        pa.field("price_cap", pa.float64(), nullable=True),
        pa.field("price_floor", pa.float64(), nullable=True),
        pa.field("take_profit_price", pa.float64(), nullable=True),
        pa.field("stop_loss_price", pa.float64(), nullable=True),
        pa.field("candle_close_price", pa.float64(), nullable=True),
        pa.field("confidence", pa.float64(), nullable=True),
        pa.field("urgency", pa.float64(), nullable=True),
        pa.field("chain_id", pa.string(), nullable=True),
        pa.field("chain_sequence", pa.int32(), nullable=True),
        pa.field("nested_instructions", pa.string(), nullable=True),
    ]
)

# Required columns for ALL instruction types
REQUIRED_COLUMNS = [
    "timestamp",
    "instruction_id",
    "instruction_type",
    "instrument_id",
    "strategy_id",
    "quantity",
    "benchmark_price",
]

# DEPRECATED: Kept for backward compatibility during migration
DIRECTION_COLUMNS = ["direction", "instruction_type"]

# DEPRECATED: signal_id is now instruction_id
# This constant exists only for backward compatibility during migration
LEGACY_SIGNAL_ID_COLUMN = "signal_id"


# =============================================================================
# VALIDATION ERRORS
# =============================================================================


class InstructionValidationError(Exception):
    """Raised when instruction validation fails."""

    def __init__(self, errors: list[str]):
        self.errors = errors
        super().__init__(f"Instruction validation failed: {errors}")


# =============================================================================
# VALIDATION FUNCTIONS
# =============================================================================


class InstructionValidator:
    """
    Validates strategy instruction dataframes against the centralized schema.

    Key validation rules:
    - instruction_type is MANDATORY
    - instruction_id is MANDATORY
    - quantity is MANDATORY (must be > 0)
    - benchmark_price is MANDATORY (must be > 0)
    - direction is REQUIRED for TRADE/SWAP (must be -1 or 1)
    - ATOMIC instructions can only contain on-chain types (NOT TRADE)

    Usage:
        validator = InstructionValidator()

        # Validate a DataFrame
        errors = validator.validate(df)
        if errors:
            logger.info("Validation errors: %s", errors)

        # Validate a parquet file
        errors = validator.validate_file("instructions.parquet")
    """

    def __init__(self, strict: bool = True, allow_legacy_signal_id: bool = True):
        """
        Initialize validator.

        Args:
            strict: If True, validate all constraints strictly
            allow_legacy_signal_id: If True, accept signal_id as alias for instruction_id
        """
        self.strict = strict
        self.allow_legacy_signal_id = allow_legacy_signal_id

    def validate(self, df: pd.DataFrame | pa.Table) -> list[str]:
        """
        Validate an instruction DataFrame.

        Args:
            df: pandas DataFrame or pyarrow Table to validate

        Returns:
            List of validation error messages (empty if valid)
        """
        errors: list[str] = []

        # Convert to pandas if needed
        if hasattr(df, "to_pandas"):
            df = df.to_pandas()  # pyright: ignore[reportCallIssue]
        if not isinstance(df, pd.DataFrame):
            return ["Input must be a pandas DataFrame or pyarrow Table"]

        # Handle legacy signal_id -> instruction_id migration
        df = self._handle_legacy_signal_id(df, errors)

        # Check required columns (stop early if missing)
        for col in REQUIRED_COLUMNS:
            if col not in df.columns:
                errors.append(f"Missing required column: {col}")
        if errors:
            return errors

        # Run all sub-validators
        self._validate_instruction_types(df, errors)
        self._validate_direction(df, errors)
        self._validate_atomic_instructions(df, errors)
        self._validate_quantity(df, errors)
        self._validate_benchmark_price(df, errors)
        self._validate_instruction_id(df, errors)
        self._validate_timestamp_type(df, errors)
        self._validate_strategy_id_format(df, errors)
        self._validate_instrument_id_format(df, errors)
        self._validate_optional_fields(df, errors)

        return errors

    def _handle_legacy_signal_id(self, df: pd.DataFrame, errors: list[str]) -> pd.DataFrame:
        """Handle legacy signal_id -> instruction_id migration."""
        set(df.columns)
        has_instruction_id = "instruction_id" in df.columns
        has_legacy_signal_id = LEGACY_SIGNAL_ID_COLUMN in df.columns

        if not has_instruction_id and has_legacy_signal_id:
            if self.allow_legacy_signal_id:
                df = df.rename(columns={LEGACY_SIGNAL_ID_COLUMN: "instruction_id"})
                logger.warning(
                    "DEPRECATED: signal_id column found. Use instruction_id instead. "
                    "Auto-renaming for backward compatibility."
                )
            else:
                errors.append("signal_id is DEPRECATED. Use instruction_id instead.")

        return df

    def _validate_instruction_types(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate instruction_type values are present and valid."""
        null_type_count = df["instruction_type"].isna().sum()
        if null_type_count > 0:
            errors.append(f"instruction_type is REQUIRED but has {null_type_count} null values")

        invalid_types = (
            df[~df["instruction_type"].isin(VALID_INSTRUCTION_TYPES)]["instruction_type"]
            .dropna()
            .unique()
        )
        if len(invalid_types) > 0:
            errors.append(
                f"Invalid instruction_type values: {list(invalid_types)}. Must be one of {VALID_INSTRUCTION_TYPES}"
            )

        # Check for deprecated instruction types and warn
        deprecated_mask = df["instruction_type"].isin(DEPRECATED_INSTRUCTION_TYPES)
        if deprecated_mask.any():
            deprecated_count = deprecated_mask.sum()
            deprecated_types = df[deprecated_mask]["instruction_type"].unique().tolist()
            logger.warning(
                "DEPRECATED instruction types found: %s (%s instructions). "
                "WITHDRAW is deprecated - balance changes are handled by strategy layer. "
                "Use UNSTAKE for staking withdrawals.",
                deprecated_types,
                deprecated_count,
            )

    def _validate_direction(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate direction values for TRADE/SWAP instructions."""
        trade_swap_mask = df["instruction_type"].isin(DIRECTION_REQUIRED_TYPES)
        if not trade_swap_mask.any():
            return

        trade_swap_df = df[trade_swap_mask]

        if "direction" not in df.columns:
            errors.append(
                f"direction column REQUIRED for TRADE/SWAP instructions ({trade_swap_mask.sum()} rows)"
            )
            return

        # Check for missing direction in TRADE/SWAP rows
        missing_direction = trade_swap_df[trade_swap_df["direction"].isna()]
        if len(missing_direction) > 0:
            errors.append(f"{len(missing_direction)} TRADE/SWAP instructions missing direction")

        # Check direction values are valid (-1 or 1, NOT 0)
        non_null_trade_swap = trade_swap_df[trade_swap_df["direction"].notna()]
        invalid_dirs = non_null_trade_swap[~non_null_trade_swap["direction"].isin(VALID_DIRECTIONS)]
        if len(invalid_dirs) > 0:
            bad_vals = invalid_dirs["direction"].unique().tolist()
            errors.append(
                f"TRADE/SWAP direction must be -1 (sell) or 1 (buy), got: {bad_vals}. Note: 0 is no longer valid."
            )

    def _validate_atomic_instructions(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate ATOMIC instruction nested_instructions JSON content."""
        atomic_mask = df["instruction_type"] == "ATOMIC"
        if not atomic_mask.any():
            return

        atomic_df = df[atomic_mask]

        if "nested_instructions" not in df.columns:
            errors.append("ATOMIC instructions require nested_instructions column")
            return

        for idx, row in atomic_df.iterrows():
            nested_json = row.get("nested_instructions")
            if not nested_json or pd.isna(nested_json):
                errors.append(f"ATOMIC instruction at index {idx} has empty nested_instructions")
                continue

            try:
                nested_raw: object = json.loads(str(nested_json))
                nested: list[object] = list(nested_raw) if isinstance(nested_raw, list) else []
                for i, ni in enumerate(nested):
                    if not isinstance(ni, dict):
                        continue
                    ni_type = ni.get("instruction_type")
                    if ni_type not in ATOMIC_COMPATIBLE_TYPES:
                        errors.append(
                            f"ATOMIC instruction at index {idx} contains invalid "
                            f"nested type '{ni_type}' at position {i}. "
                            f"ATOMIC can only contain on-chain types: {ATOMIC_COMPATIBLE_TYPES}. "
                            f"TRADE is NOT allowed (it's CeFi/off-chain)."
                        )
            except json.JSONDecodeError as e:
                errors.append(f"ATOMIC instruction at index {idx} has invalid JSON: {e}")

    def _validate_quantity(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate quantity is present and positive."""
        null_qty_count = df["quantity"].isna().sum()
        if null_qty_count > 0:
            errors.append(f"quantity is REQUIRED but has {null_qty_count} null values")

        invalid_qty = (df["quantity"] <= 0) & df["quantity"].notna()
        if invalid_qty.sum() > 0:
            errors.append(f"quantity must be > 0: {invalid_qty.sum()} invalid values")

    def _validate_benchmark_price(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate benchmark_price is present and positive."""
        # Check for zero values
        zero_count = (df["benchmark_price"].abs() < 1e-12).sum()
        if zero_count > 0:
            errors.append(
                f"benchmark_price contains {zero_count} zero values. "
                f"benchmark_price must be > 0 for execution alpha calculation."
            )

        # Check for negative values
        negative_count = (df["benchmark_price"] < 0).sum()
        if negative_count > 0:
            errors.append(
                f"benchmark_price contains {negative_count} negative values. benchmark_price must be > 0."
            )

        # Check for NaN values
        nan_count = df["benchmark_price"].isna().sum()
        if nan_count > 0:
            errors.append(
                f"benchmark_price contains {nan_count} NaN values. benchmark_price must be > 0."
            )

    def _validate_instruction_id(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate instruction_id is present and unique."""
        null_id_count = df["instruction_id"].isna().sum()
        if null_id_count > 0:
            errors.append(f"instruction_id is REQUIRED but has {null_id_count} null values")

        # Check for duplicate instruction_ids
        if self.strict:
            dup_count = df["instruction_id"].duplicated().sum()
            if dup_count > 0:
                errors.append(f"instruction_id must be unique: {dup_count} duplicates found")

    def _validate_timestamp_type(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate timestamp column dtype is int64."""
        if not df["timestamp"].dtype.name.startswith("int"):
            errors.append(
                f"timestamp column must be int64 (nanoseconds), got {df['timestamp'].dtype}"
            )

    def _validate_strategy_id_format(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate strategy_id format matches expected pattern."""
        unique_strategy_ids = df["strategy_id"].unique()
        for sid in unique_strategy_ids:
            if sid and not validate_strategy_id(str(sid)):
                errors.append(
                    f"Invalid strategy_id format: {sid}. "
                    f"Expected: {{CATEGORY}}_{{ASSET}}_{{description}}_{{MODE}}_{{TIMEFRAME}}_V{{N}}"
                )

    def _validate_instrument_id_format(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate instrument_id format matches VENUE:TYPE:SYMBOL pattern."""
        unique_inst_ids = df["instrument_id"].unique()
        for inst_id in unique_inst_ids:
            if inst_id and str(inst_id).count(":") < 2:
                errors.append(
                    f"Invalid instrument_id format: {inst_id}. Expected: VENUE:TYPE:SYMBOL"
                )

    def _validate_optional_fields(self, df: pd.DataFrame, errors: list[str]) -> None:
        """Validate optional fields (confidence, urgency, price bounds, chains)."""
        # Validate confidence/urgency are in [0, 1]
        bounded_cols = ["confidence", "urgency"]
        for col in bounded_cols:
            if col in df.columns:
                non_null = df[col].notna()
                out_of_range = ((df[col] < 0) | (df[col] > 1)) & non_null
                if out_of_range.sum() > 0:
                    errors.append(
                        f"{col} contains {out_of_range.sum()} values outside [0, 1] range"
                    )

        # Validate price bounds (price_cap >= price_floor if both set)
        if "price_cap" in df.columns and "price_floor" in df.columns:
            both_set = df["price_cap"].notna() & df["price_floor"].notna()
            if both_set.any():
                invalid_bounds = df[both_set]["price_cap"] < df[both_set]["price_floor"]
                if invalid_bounds.sum() > 0:
                    errors.append(
                        f"price_cap must be >= price_floor: {invalid_bounds.sum()} violations"
                    )

        # Validate chain_sequence is positive if chain_id is set
        if "chain_id" in df.columns and "chain_sequence" in df.columns:
            has_chain = df["chain_id"].notna()
            if has_chain.any():
                missing_seq = has_chain & df["chain_sequence"].isna()
                if missing_seq.sum() > 0:
                    errors.append(
                        f"{missing_seq.sum()} rows have chain_id but missing chain_sequence"
                    )

                invalid_seq = has_chain & (df["chain_sequence"] <= 0)
                if invalid_seq.sum() > 0:
                    errors.append(f"chain_sequence must be > 0: {invalid_seq.sum()} invalid values")

    def validate_or_raise(self, df: pd.DataFrame | pa.Table) -> None:
        """
        Validate an instruction DataFrame and raise if invalid.

        Args:
            df: DataFrame to validate

        Raises:
            InstructionValidationError: If validation fails
        """
        errors = self.validate(df)
        if errors:
            raise InstructionValidationError(errors)


def validate_instruction_dataframe(
    df: pd.DataFrame | pa.Table, strict: bool = True, allow_legacy_signal_id: bool = True
) -> list[str]:
    """
    Convenience function to validate an instruction DataFrame.

    Args:
        df: pandas DataFrame or pyarrow Table to validate
        strict: If True, validate all constraints strictly
        allow_legacy_signal_id: If True, accept signal_id as alias for instruction_id

    Returns:
        List of validation error messages (empty if valid)
    """
    validator = InstructionValidator(strict=strict, allow_legacy_signal_id=allow_legacy_signal_id)
    return validator.validate(df)


def validate_instruction_parquet(
    path: str | Path, strict: bool = True, allow_legacy_signal_id: bool = True
) -> list[str]:
    """
    Validate an instruction parquet file.

    Args:
        path: Path to parquet file
        strict: If True, validate all constraints strictly
        allow_legacy_signal_id: If True, accept signal_id as alias for instruction_id

    Returns:
        List of validation error messages (empty if valid)
    """
    path = Path(path)

    if not path.exists():
        return [f"Instruction file not found: {path}"]

    try:
        table = pq.read_table(path)
        df = table.to_pandas()
    except (OSError, PermissionError, ValueError) as e:
        return [f"Failed to read parquet file {path}: {e}"]

    return validate_instruction_dataframe(
        df, strict=strict, allow_legacy_signal_id=allow_legacy_signal_id
    )


def get_instruction_pyarrow_schema() -> pa.Schema:
    """
    Get the PyArrow schema for instruction parquet files.

    Returns:
        PyArrow Schema object
    """
    return INSTRUCTION_SCHEMA


def migrate_legacy_dataframe(df: pd.DataFrame | pa.Table) -> pd.DataFrame:
    """
    Migrate a legacy instruction DataFrame to the new schema.

    Handles:
    - signal_id -> instruction_id rename
    - price -> price_cap/price_floor (if applicable)
    - notional removal (kept as-is, just not validated)

    Args:
        df: pandas DataFrame with legacy schema

    Returns:
        DataFrame with migrated schema
    """

    if hasattr(df, "to_pandas"):
        df = df.to_pandas()  # pyright: ignore[reportCallIssue]

    df = df.copy()

    # Rename signal_id to instruction_id
    if LEGACY_SIGNAL_ID_COLUMN in df.columns and "instruction_id" not in df.columns:
        df = df.rename(columns={LEGACY_SIGNAL_ID_COLUMN: "instruction_id"})
        logger.info("Migrated signal_id -> instruction_id")

    # Migrate price to price_cap (assuming it was used as a limit)
    if "price" in df.columns and "price_cap" not in df.columns:
        df["price_cap"] = df["price"]
        logger.info("Migrated price -> price_cap")

    return df
